apiVersion: apps/v1
kind: Deployment
metadata:
  name: "locust-plugins-timescaledb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-plugins-timescaledb
  template:
    metadata:
      labels:
        app: locust-plugins-timescaledb
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: locust-plugins-timescaledb
        image: {{ .Values.timescale_db.image }}
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.timescale_db.password }}
        - name: TIMESCALEDB_TELEMETRY
          value: "off"
#        volumeMounts:
#        - mountPath: /var/lib/postgresql/data
#          name: postgres-data
#      volumes:
#      - name: postgres-data
#        persistentVolumeClaim:
#          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: "locust-plugins-timescaledb"
spec:
  type: {{ .Values.timescale_db.service.type }}
  ports:
  - port: {{ .Values.timescale_db.port }}
    targetPort: 5432
  selector:
    app: "locust-plugins-timescaledb"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "locust.fullname" . }}-grafana"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ template "locust.fullname" . }}-grafana"
  template:
    metadata:
      labels:
        app: "{{ template "locust.fullname" . }}-grafana"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: "{{ template "locust.fullname" . }}-grafana"
        image: "{{ .Values.locust_dashboard.image }}"
        ports:
        - containerPort: 3000
        env:
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_LOG_LEVEL
          value: "warn"
#        volumeMounts:
#        - mountPath: /var/lib/grafana
#          name: grafana-data
#      volumes:
#      - name: grafana-data
#        persistentVolumeClaim:
#          claimName: grafana-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "locust.fullname" . }}-grafana"
spec:
  type: "{{ .Values.locust_dashboard.service.type }}"
  ports:
  - port: {{ .Values.locust_dashboard.port }}
    targetPort: 3000
  selector:
    app: "{{ template "locust.fullname" . }}-grafana"
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: grafana-pvc
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi

