name: ci

on:
  push:
    paths:
      - "build_dashboard/**"
    branches:
      - "main"


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build grafana and push
        uses: docker/build-push-action@v5
        with:
          context: build_dashboard/locust-grafana
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sky5367/locust-grafana:3

      - name: Build timescale and push
        uses: docker/build-push-action@v5
        with:
          context: build_dashboard/locust-timescale
          platforms: linux/amd64,linux/arm64
          push: true
          tags: sky5367/locust-timescale:6